---
title: "Lab 7 Rank-Based Test"
author: "Renee Albrecht"
date: "November 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hi it's Renee! I created this repo and markdown document!! 

Hey it's Madeline! Always happy to kelp out

I'm going to make some histograms
```{r}
library(tidyverse)
kermit = read_csv("kermit.csv")
View(kermit)

#going to ask if there is a significant difference in ranks in male and female students. 
#Is there a significant difference in pre and post ranks. 

```

```{r}
#Making a histogram

kermit_hist = ggplot(kermit, aes(x = Score.pre))+
  geom_histogram()+
  facet_wrap(~ Gender)+
  theme_classic()

kermit_hist
```

Creator: doing some rank-based tests 

```{r}

#Is there a significant difference in pre-talk Kermit scores for males and females? 

#Unpaired: Mann-Whitney U

mwu_kermit <- kermit %>%
  wilcox.test(Score.pre ~ Gender, data = .)

mwu_kermit


```

Collaborator:

Compare the pre and post talk ranks

Is there a significant difference in Kermit ranks for pre-talk and post-talk scores?

```{r}
#H0 : no difference in ranks between pre and post talk kermit appreciation
#HA : difference in ranks between pre and post talk kermiet appreciation

wsr_kermit = wilcox.test(kermit$Score.pre, kermit$Score.post, paired = TRUE)
wsr_kermit

# There is no significant difference in kermit rankings before and after his talk (summary...)
```

